title: <p align="center"> Nhi Nguyen </p>
logo: "img/crop_ava_NN.png"


description:

  <p align="center">
  <a href="pdf/Lebenslauf_NhiNguyen_DS.pdf">Resume</a> 
  <br> Darmstadt, Germany
  <br> Nhi.nguyenpb@gmail.com
  <br> Data Science (M.Sc) | Psychology (B.Sc) | RStudio | Python | Machine Learning | Interactive Dashboard | Data Analyst
  </p>

  # <p align="justify">
  # Ich bin eine engagierte und selbstmotivierte <b>Data Scientist</b>, die nach neuen Herausforderungen sucht, die mit meinen Werten und Karrierezielen übereinstimmen. 
  # <br>
  # Mit einem Hintergrund in Psychologie (B.Sc) und Data Science (M.Sc) bringe ich eine einzigartige Kombination aus analytischem Denken und technischer Expertise mit. 
  # <br>
  # Meine Erfahrungen umfassen statistische Analysen, maschinelles Lernen und die Entwicklung interaktiver Dashboards.
  # <br><br>
  # </p>
  
theme: jekyll-theme-minimal
