title: <p align="center"> Nhi Nguyen </p>
logo: "img/crop_ava_NN.png"


description:

  <p align="center">
  Darmstadt, Germany

  <br> <a href="pdf/Lebenslauf_Nhi_Nguyen.pdf">Resume</a>   
  <br> Nhi.nguyenpb@gmail.com
  </p>

  # <p align="justify">
  # Ich bin eine engagierte und selbstmotivierte <b>Data Scientist</b>, die nach neuen Herausforderungen sucht, die mit meinen Werten und Karrierezielen übereinstimmen. 
  # <br>
  # Mit einem Hintergrund in Psychologie (B.Sc) und Data Science (M.Sc) bringe ich eine einzigartige Kombination aus analytischem Denken und technischer Expertise mit. 
  # <br>
  # Meine Erfahrungen umfassen statistische Analysen, maschinelles Lernen und die Entwicklung interaktiver Dashboards.
  # <br><br>
  # </p>
  
theme: jekyll-theme-minimal
