title: <p align="center"> Nhi Nguyen </p>
logo: "/img/Nhi Nguyen.jpg"

description:

  <p align="center">
  Darmstadt, Germany

  <br> nhi.nguyenpb@gmail.com
  <br> <a href="pdf/Lebenslauf_Nhi_Nguyen.pdf">Resume</a> 
  </p>
  
  
theme: jekyll-theme-minimal
